name: Run Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs: 
  # SonarCloud:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
  #     - name: SonarQube Scan
  #       uses: SonarSource/sonarqube-scan-action@v5
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONAR_HOST_URL: https://sonarcloud.io
  #       with:
  #         args: >
  #           -Dsonar.projectKey=sharnitha-sonarcloud1_vue3-app
  #           -Dsonar.organization=sharnitha-sonarcloud1
      
  #     - name: SonarQube Quality Gate check
  #       id: sonarqube-quality-gate-check
  #       uses: SonarSource/sonarqube-scan-action@v5
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONAR_HOST_URL: https://sonarcloud.io
  #       with:
  #         args: >
  #           -Dsonar.projectKey=sharnitha-sonarcloud1_vue3-app
  #           -Dsonar.organization=sharnitha-sonarcloud1
      # The possible outputs of the `quality-gate-status` variable are `PASSED`, `WARN` or `FAILED`.
      # - name: "Example show SonarQube Quality Gate Status value"
      #   run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
            
  build_Push-acr:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2 
        - name: Docker build
          run: |
            docker build --target dev -t Sharnithadockerimagstore.azurecr.io/frontend:${{ github.run_id }} .
        - name: Run Trivy scan
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: "Sharnithadockerimagstore.azurecr.io/frontend:${{ github.run_id }}"
            format: "table"
            exit-code: 1
            ignore-unfixed: true
            severity: "CRITICAL,HIGH"
            
        - name: Docker build
          run: |
            docker login Sharnithadockerimagstore.azurecr.io -u sharnithadockerimagstore -p ${{secrets.pat}}
            docker push Sharnithadockerimagstore.azurecr.io/frontend:${{ github.run_id }}  
          

            # - name: Run SonarCloud analysis for Vue using `sonar`
      #   run: |
      #     npm install -g sonar
      #     sonar \
      #       -Dsonar.host.url=https://sonarcloud.io \
      #       -Dsonar.token=ac35b1a790aa492f9bbe0a1adcd52ea77ff4adb4
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@v2
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: >
      #       -Dsonar.projectKey=Vue3 app
      #       -Dsonar.organization=Sharnitha-sonarcloud1
      
      # - name: Docker build
      #   run: |
      #     docker login thisonetypeofstoragingdockerimage.azurecr.io -u thisonetypeofstoragingdockerimage -p ${{secrets.pat}}
      #     docker push thisonetypeofstoragingdockerimage.azurecr.io/frontend:${{ github.run_id }}  
     
