name: Run Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main 

jobs: 
  build_Push-acr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: Docker build
        run: docker build -t thisonetypeofstoragingdockerimage.azurecr.io/frontend:${{ github.run_id }} .
      - name: Run SonarCloud analysis for Vue using `sonar`
        run: |
          npm install -g sonar
          sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=ac35b1a790aa492f9bbe0a1adcd52ea77ff4adb4
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@v2
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: >
      #       -Dsonar.projectKey=Sharnitha-sonarcloud1
      #       -Dsonar.organization=Sharnitha-sonarcloud1
      
      # - name: Docker build
      #   run: |
      #     docker login thisonetypeofstoragingdockerimage.azurecr.io -u thisonetypeofstoragingdockerimage -p ${{secrets.pat}}
      #     docker push thisonetypeofstoragingdockerimage.azurecr.io/frontend:${{ github.run_id }}  
     
