name: Run Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: Docker build
        run: docker build -t test .

  Push_Image-ACR:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Docker build
        run: |
          docker login thisonetypeofstoragingdockerimage.azurecr.io -u thisonetypeofstoragingdockerimage -p ${{secrets.pat}}
          docker push thisonetypeofstoragingdockerimage.azurecr.io/frontend:${{ github.run_id }}  
     
